// Auto-generated from vite.config.js
// Generated on: 2025-12-03T10:59:02.992Z
// DO NOT EDIT THIS FILE MANUALLY

/**
 * Rollup input configuration for Vite build
 * Contains absolute paths to HTML entry points
 */
export const rollupInputs = {
  "Главная": "D:\\Проекты\\owenkomplekt\\owenkomplekt\\src\\html\\index.html",
  "ui_kit": "D:\\Проекты\\owenkomplekt\\owenkomplekt\\src\\html\\ui-kit.html",
  "Каталог_главная": "D:\\Проекты\\owenkomplekt\\owenkomplekt\\src\\html\\catalog.html",
  "Каталог": "D:\\Проекты\\owenkomplekt\\owenkomplekt\\src\\html\\OKATEC-Inverters.html",
  "Каталог_подкатегория": "D:\\Проекты\\owenkomplekt\\owenkomplekt\\src\\html\\catalog-subcategory.html",
  "Каталог_детальная_страница": "D:\\Проекты\\owenkomplekt\\owenkomplekt\\src\\html\\catalog-detail.html",
  "Путая_корзина": "D:\\Проекты\\owenkomplekt\\owenkomplekt\\src\\html\\basket-empty.html",
  "Корзина": "D:\\Проекты\\owenkomplekt\\owenkomplekt\\src\\html\\basket.html",
  "Корзина_оформление_заказа": "D:\\Проекты\\owenkomplekt\\owenkomplekt\\src\\html\\basket-order.html",
  "О_нас": "D:\\Проекты\\owenkomplekt\\owenkomplekt\\src\\html\\about.html",
  "Дилерам": "D:\\Проекты\\owenkomplekt\\owenkomplekt\\src\\html\\dealer.html",
  "Партнерская_программа": "D:\\Проекты\\owenkomplekt\\owenkomplekt\\src\\html\\partner-program.html",
  "Услуги": "D:\\Проекты\\owenkomplekt\\owenkomplekt\\src\\html\\services.html",
  "Производство": "D:\\Проекты\\owenkomplekt\\owenkomplekt\\src\\html\\production.html",
  "Наши_проекты": "D:\\Проекты\\owenkomplekt\\owenkomplekt\\src\\html\\projects.html",
  "Новости_и_полезные_материалы": "D:\\Проекты\\owenkomplekt\\owenkomplekt\\src\\html\\news.html",
  "Страница_проекта": "D:\\Проекты\\owenkomplekt\\owenkomplekt\\src\\html\\project-page.html",
  "Контакты": "D:\\Проекты\\owenkomplekt\\owenkomplekt\\src\\html\\contacts.html"
};

/**
 * Relative paths from src directory
 * Useful for navigation within the project
 */
export const relativePaths = {
  "Главная": "html\\index.html",
  "ui_kit": "html\\ui-kit.html",
  "Каталог_главная": "html\\catalog.html",
  "Каталог": "html\\OKATEC-Inverters.html",
  "Каталог_подкатегория": "html\\catalog-subcategory.html",
  "Каталог_детальная_страница": "html\\catalog-detail.html",
  "Путая_корзина": "html\\basket-empty.html",
  "Корзина": "html\\basket.html",
  "Корзина_оформление_заказа": "html\\basket-order.html",
  "О_нас": "html\\about.html",
  "Дилерам": "html\\dealer.html",
  "Партнерская_программа": "html\\partner-program.html",
  "Услуги": "html\\services.html",
  "Производство": "html\\production.html",
  "Наши_проекты": "html\\projects.html",
  "Новости_и_полезные_материалы": "html\\news.html",
  "Страница_проекта": "html\\project-page.html",
  "Контакты": "html\\contacts.html"
};

/**
 * List of available page keys
 */
export const pageKeys = [
  "Главная",
  "ui_kit",
  "Каталог_главная",
  "Каталог",
  "Каталог_подкатегория",
  "Каталог_детальная_страница",
  "Путая_корзина",
  "Корзина",
  "Корзина_оформление_заказа",
  "О_нас",
  "Дилерам",
  "Партнерская_программа",
  "Услуги",
  "Производство",
  "Наши_проекты",
  "Новости_и_полезные_материалы",
  "Страница_проекта",
  "Контакты"
];

/**
 * Get the path for a specific page
 * @param {string} pageKey - Key of the page (index, ui_kit, error, etc.)
 * @returns {string|null} Absolute path or null if not found
 */
export function getPagePath(pageKey) {
  return rollupInputs[pageKey] || null;
}

/**
 * Get the relative path for a specific page
 * @param {string} pageKey - Key of the page (index, ui_kit, error, etc.)
 * @returns {string|null} Relative path from src directory or null if not found
 */
export function getPageRelativePath(pageKey) {
  return relativePaths[pageKey] || null;
}

/**
 * Check if a page key exists
 * @param {string} pageKey - Key to check
 * @returns {boolean} True if the page exists
 */
export function hasPage(pageKey) {
  return pageKey in rollupInputs;
}

export default rollupInputs;
